import type { JourneyTrip } from './types'

const u = (id: string) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1200&q=80`

export const MOCK_JOURNEYS: JourneyTrip[] = [
  {
    id: '1',
    name: 'Himachal Backpacking',
    description: 'High passes, ridge camps, and slow mornings above the treeline.',
    status: 'ongoing',
    image: u('1626621341517-bbf3d9990a23'),
    dates: 'Mar 12 – Mar 24, 2026',
    destinations: ['Manali', 'Spiti', 'Kasol'],
    budget: '$1,840',
    budgetValue: 1840,
    duration: '12 nights',
    travelers: 3,
    weatherTemp: '14°C',
    weatherCond: 'Crisp alpine',
    progress: 72,
    completedDays: 8,
    totalDays: 12,
  },
  {
    id: '2',
    name: 'Bali Summer Escape',
    description: 'Cliff clubs, rice terraces, and sunrise reef sessions.',
    status: 'ongoing',
    image: u('1537996194471-e657df975ab4'),
    dates: 'Jun 3 – Jun 14, 2026',
    destinations: ['Ubud', 'Canggu', 'Uluwatu'],
    budget: '$2,260',
    budgetValue: 2260,
    duration: '11 nights',
    travelers: 2,
    weatherTemp: '28°C',
    weatherCond: 'Humid · Sun',
    progress: 38,
    completedDays: 4,
    totalDays: 11,
  },
  {
    id: '3',
    name: 'Switzerland Adventure',
    description: 'Glacier express, fondue nights, and lake promenade walks.',
    status: 'upcoming',
    image: u('1530122037265-a5f1f91d3b99'),
    dates: 'Sep 1 – Sep 9, 2026',
    destinations: ['Zermatt', 'Interlaken', 'Zürich'],
    budget: '$4,020',
    budgetValue: 4020,
    duration: '8 nights',
    travelers: 4,
    weatherTemp: '18°C',
    weatherCond: 'Mild · Mix',
    progress: 0,
    completedDays: 0,
    totalDays: 8,
  },
  {
    id: '4',
    name: 'Goa Roadtrip',
    description: 'Coastal drives, spice markets, and golden-hour sets.',
    status: 'completed',
    image: u('1512343879784-a960bf40e7f2'),
    dates: 'Jan 4 – Jan 12, 2026',
    destinations: ['North Goa', 'Palolem'],
    budget: '$980',
    budgetValue: 980,
    duration: '8 nights',
    travelers: 3,
    weatherTemp: '29°C',
    weatherCond: 'Clear',
    progress: 100,
    completedDays: 8,
    totalDays: 8,
  },
  {
    id: '5',
    name: 'Tokyo Experience',
    description: 'Neon alleys, omakase counters, and quiet shrine mornings.',
    status: 'completed',
    image: u('1540959733332-eab4deabeeaf'),
    dates: 'Nov 2 – Nov 10, 2025',
    destinations: ['Shibuya', 'Asakusa', 'Kyoto day trip'],
    budget: '$3,400',
    budgetValue: 3400,
    duration: '8 nights',
    travelers: 2,
    weatherTemp: '17°C',
    weatherCond: 'Cool · Dry',
    progress: 100,
    completedDays: 8,
    totalDays: 8,
  },
]
